# Output Model Layers

In [1]:
import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFBertForMaskedLM
from transformers import TFCamembertForMaskedLM

In [2]:
### Build Model
bert_input = tf.keras.Input(shape=(32), dtype='int32', name='bert_input')
x = TFCamembertForMaskedLM.from_pretrained("jplu/tf-camembert-base")(bert_input)[0]
x = tf.keras.layers.Reshape((32*32005,))(x)
dense_out = tf.keras.layers.Dense(2, activation='softmax')(x)
model = tf.keras.Model(bert_input, dense_out, name='model')

In [3]:
### Load Fine-Tuned Weights
checkpointPath = "../project_PunctuatorBERTTensorFlow2/Models/20200530_161559/cp-001.ckpt"
model.load_weights(checkpointPath)

In [4]:
### write the output file
nameOutFile = 'modelLayers.txt'
outFile = open(nameOutFile, 'w')
for i in range(len(model.trainable_variables)):
    outFile.write(model.trainable_variables[i].name)
    outFile.write(str(model.trainable_variables[i].shape))
    outFile.write("\n")

In [8]:
model.trainable_variables[194][0:]

<tf.Tensor: shape=(32005, 768), dtype=float32, numpy=
array([[-0.05737098,  0.0300844 ,  0.00174185, ...,  0.10549821,
         0.01205398, -0.04350847],
       [ 0.0021368 , -0.04996245, -0.00753174, ..., -0.0278854 ,
        -0.01016846, -0.02549173],
       [-0.02472154,  0.12818374,  0.05860885, ...,  0.01217413,
         0.06726432,  0.05333984],
       ...,
       [-0.03227867,  0.11877602,  0.07306319, ...,  0.02041066,
         0.1475172 , -0.1480211 ],
       [-0.12455108, -0.11612724, -0.08341085, ..., -0.12297679,
         0.00784095, -0.19798043],
       [ 0.03410634, -0.01845361,  0.01806762, ..., -0.02796204,
         0.03184153, -0.02818965]], dtype=float32)>

In [9]:
tensor = tf.random.uniform(shape=[1, 32, 768])
tensor

<tf.Tensor: shape=(1, 32, 768), dtype=float32, numpy=
array([[[0.99574983, 0.73108315, 0.6375716 , ..., 0.26610458,
         0.241279  , 0.67206335],
        [0.78498983, 0.33794987, 0.36713052, ..., 0.6345172 ,
         0.80781126, 0.52040935],
        [0.46350133, 0.86313176, 0.32333338, ..., 0.8807298 ,
         0.7502372 , 0.92421615],
        ...,
        [0.49624467, 0.12078679, 0.3023466 , ..., 0.07936347,
         0.22699249, 0.27971482],
        [0.91258204, 0.85015917, 0.9081558 , ..., 0.71023154,
         0.0611136 , 0.03149307],
        [0.51146805, 0.19469225, 0.5085585 , ..., 0.48693717,
         0.19238722, 0.10358763]]], dtype=float32)>

In [10]:
tensorQ = model.trainable_variables[194][0:]
tensorQ

<tf.Tensor: shape=(32005, 768), dtype=float32, numpy=
array([[-0.05737098,  0.0300844 ,  0.00174185, ...,  0.10549821,
         0.01205398, -0.04350847],
       [ 0.0021368 , -0.04996245, -0.00753174, ..., -0.0278854 ,
        -0.01016846, -0.02549173],
       [-0.02472154,  0.12818374,  0.05860885, ...,  0.01217413,
         0.06726432,  0.05333984],
       ...,
       [-0.03227867,  0.11877602,  0.07306319, ...,  0.02041066,
         0.1475172 , -0.1480211 ],
       [-0.12455108, -0.11612724, -0.08341085, ..., -0.12297679,
         0.00784095, -0.19798043],
       [ 0.03410634, -0.01845361,  0.01806762, ..., -0.02796204,
         0.03184153, -0.02818965]], dtype=float32)>